@echo off
echo Starting Docker Containers...
docker compose up --build -d

echo Waiting for services to start...
timeout /t 10 /nobreak >nul

echo Opening Streamlit App...
start http://localhost:8501

echo Showing Docker Logs (Press Ctrl+C to exit logs, containers will keep running)...
docker compose logs -f
